Reliability improvements

diff --git a/files/usr/local/bin/media_mount b/files/usr/local/bin/media_mount
--- a/files/usr/local/bin/media_mount
+++ b/files/usr/local/bin/media_mount
@@ -1,35 +1,34 @@
 #!/usr/bin/env bash
 
 LOGFILE="/var/log/diskplayer.log"
+MOUNTPOINT="/mnt/floppy"
 
 function log() {
     echo "$(date) ${1}" | tee -a ${LOGFILE}
 }
 
 function play() {
+    log "Last status: $?"
     mpc stop && log "Stopped current playback"
     mpc clear && log "Cleaned the queue"
-    cat /mnt/floppy/media.m3u | mpc add && log "Queued an album"
-    log "Last status: $?"
+    cat ${MOUNTPOINT}/media.m3u | mpc add && log "Queued an album"
     mpc add file:///usr/local/share/diskplayer/bleep.mp3 && log "Queued the bleep"
     mpc consume on
     mpc random off
     mpc volume 30
-    mpc play 1 && log "Starting playback"
-    /usr/bin/umount --verbose /mnt/floppy && log "Unmounting floppy"
-    echo "1" > /etc/diskplayer_status
+    mpc play 1 && log "Starting playback" && echo "1" > /etc/diskplayer_status
 }
 
 function retry_mount() {
     for i in `seq 1 5`; do
-        if grep -qs "/mnt/floppy" /proc/mounts; then
+        if grep -qs "${MOUNTPOINT}" /proc/mounts; then
             log "Successfully mounted a drive"
 	    sync
 	    sleep 1
             break
         else
-            log "Trying to mount ${1} to /mnt/floppy, attempt ${i}..."
-            OUTPUT=`/usr/bin/mount --verbose $1 /mnt/floppy 2>&1`
+            log "Trying to mount ${1} to ${MOUNTPOINT}, attempt ${i}..."
+            OUTPUT=`/usr/bin/systemd-mount --fsck=off $1 ${MOUNTPOINT} 2>&1`
 	    log "Mounting ${1}: ${OUTPUT}"
         fi
         log "Waiting for 2 seconds before next try"
@@ -38,6 +37,8 @@ function retry_mount() {
 }
 
 log "Start."
+log "Running as $(whoami)"
+systemctl daemon-reload
 log "Media change detected on device ${1}"
 
 sleep 1
@@ -45,18 +46,23 @@ sleep 1
 LENGTH=$(lsblk -A --json ${1} | jq '.blockdevices | length')
 
 if [ ${LENGTH} -gt 0 ]; then
-    log "Device exists on machine."
-    log "Mounting device $1 to /mnt/floppy."
-    retry_mount ${1}
-    log "We've made it here"
-    if [[ -f /mnt/floppy/media.m3u ]]; then
-        play
+    STATUS=$(cat /etc/diskplayer_status)
+    if [[ ${STATUS} = '0' ]]; then
+        log "Device exists on machine."
+        log "Mounting device $1 to ${MOUNTPOINT}."
+        retry_mount ${1}
+        log "We've made it here"
+        if [[ -f ${MOUNTPOINT}/media.m3u ]]; then
+            play
+        else
+            log "seems like mounting has failed, not doing anything :("
+        fi
     else
-        log "seems like mounting has failed, not doing anything :("
+        log "Playback status unchanged"
     fi
 else
     log "Device does not exist on machine."
-    /usr/bin/umount --verbose /mnt/floppy 2>&1 && log "Unmounted floppy successfully"
+    /usr/bin/umount --verbose ${MOUNTPOINT} 2>&1 && log "Unmounted floppy successfully"
     STATUS=$(cat /etc/diskplayer_status)
     if [[ ${STATUS} = '1' ]]; then
 	log "Stopping playback..."
